// Fichier généré automatiquement le 2026-09-03T10:38:23.168Z
// Ne pas modifier manuellement

export const lastUpdate = "10:38:23 AM 9/3/2026";

export const sources = [
    {
        "handle": "@EtienneTillierStudio",
        "name": "Etienne Tillier",
        "id": "UCUlm3shqkgVNHLomYWZsfYA",
        "theme": "Vibe Coding & Dev IA",
        "avatar": "https://ui-avatars.com/api/?name=Etienne+Tillier&background=0ea5e9&color=fff"
    },
    {
        "handle": "@Simon_bcome",
        "name": "Simon Music",
        "id": "UCaryUIRfj7KAikH_ogrOzig",
        "theme": "Business & Monétisation IA",
        "avatar": "https://ui-avatars.com/api/?name=Simon+Music&background=0ea5e9&color=fff"
    },
    {
        "handle": "@HenriExplorIA",
        "name": "Henri · ExplorIA",
        "id": "UCxx03UqvjTy9w8iomLwTSuQ",
        "theme": "Outils & Modèles IA",
        "avatar": "https://ui-avatars.com/api/?name=Henri+ExplorIA&background=0ea5e9&color=fff"
    },
    {
        "handle": "@elliottpierret",
        "name": "Elliott Pierret",
        "id": "UCnJAGhDDEPdvY2g4ipf9PMQ",
        "theme": "Vibe Coding & Dev IA",
        "avatar": "https://ui-avatars.com/api/?name=Elliott+Pierret&background=0ea5e9&color=fff"
    },
    {
        "handle": "@ousmanedf",
        "name": "Ousmane Automatise",
        "id": "UC1o5Eo5Qf12_f6D836PsoPw",
        "theme": "Agents & Automatisation",
        "avatar": "https://ui-avatars.com/api/?name=Ousmane+Automatise&background=0ea5e9&color=fff"
    },
    {
        "handle": "@yassine-sdiri",
        "name": "Yassine Sdiri",
        "id": "UC94UeaPuTt_L51RkDxj9d_w",
        "theme": "Business & Monétisation IA",
        "avatar": "https://ui-avatars.com/api/?name=Yassine+Sdiri&background=0ea5e9&color=fff"
    },
    {
        "handle": "@cedric_effi10",
        "name": "Cédric Girard",
        "id": "UCjhLy8XRh4Q0NM2CD6pFPYQ",
        "theme": "Outils & Modèles IA",
        "avatar": "https://ui-avatars.com/api/?name=Cedric+Girard&background=0ea5e9&color=fff"
    },
    {
        "handle": "@EliottMeunier",
        "name": "Eliott Meunier",
        "id": "UCPo1nFSGNkyzrA9yvtkEvIw",
        "theme": "Productivité & Second Cerveau",
        "avatar": "https://ui-avatars.com/api/?name=Eliott+Meunier&background=0ea5e9&color=fff"
    },
    {
        "handle": "@reverdybusiness",
        "name": "Lucas Reverdy",
        "id": "UCabbBG5KYGtdTibrl_XHLOw",
        "theme": "Business & Monétisation IA",
        "avatar": "https://ui-avatars.com/api/?name=Lucas+Reverdy&background=0ea5e9&color=fff"
    },
    {
        "handle": "@JulienSnsn",
        "name": "Julien Sanson",
        "id": "UCK85rF_WKv1N6ojTzVbj3yw",
        "theme": "Agents & Automatisation",
        "avatar": "https://ui-avatars.com/api/?name=Julien+Sanson&background=0ea5e9&color=fff"
    },
    {
        "handle": "@NerdyKings",
        "name": "Nerdy Kings",
        "id": "UCp7vimq7dYKiVAJLPyI0GcA",
        "theme": "Outils & Modèles IA",
        "avatar": "https://ui-avatars.com/api/?name=Nerdy+Kings&background=0ea5e9&color=fff"
    },
    {
        "handle": "@iAlan_automatise",
        "name": "iAlan",
        "id": "UCdROsT8FZ2pacpipymmmaPw",
        "theme": "Agents & Automatisation",
        "avatar": "https://ui-avatars.com/api/?name=iAlan&background=0ea5e9&color=fff"
    },
    {
        "handle": "@LouisGraffeuil",
        "name": "Louis Graffeuil",
        "id": "UChkCdoCUCNYizE8d9TXsi4A",
        "theme": "Vibe Coding & Dev IA",
        "avatar": "https://ui-avatars.com/api/?name=Louis+Graffeuil&background=0ea5e9&color=fff"
    },
    {
        "handle": "@Hugo_Buisson",
        "name": "Hugo Buisson",
        "id": "UCeZvp_y5meYlfcGCFhl6UJQ",
        "theme": "Outils & Modèles IA",
        "avatar": "https://ui-avatars.com/api/?name=Hugo+Buisson&background=0ea5e9&color=fff"
    },
    {
        "handle": "@audelalia",
        "name": "Au-delà l'IA",
        "id": "UCNSPV84q4QlUtle6MS_7v1Q",
        "theme": "Productivité & Second Cerveau",
        "avatar": "https://ui-avatars.com/api/?name=Au+dela+l+IA&background=0ea5e9&color=fff"
    },
    {
        "handle": "@thomasbssh",
        "name": "Thomas Berton",
        "id": "UCxOWUTmenPJj5V6_g2-CS1g",
        "theme": "Agents & Automatisation",
        "avatar": "https://ui-avatars.com/api/?name=Thomas+Berton&background=0ea5e9&color=fff"
    },
    {
        "handle": "@LudovicSalenne",
        "name": "Ludo Salenne",
        "id": "UCnnYqSNKKygemgmxC9PyLTw",
        "theme": "Agents & Automatisation",
        "avatar": "https://ui-avatars.com/api/?name=Ludo+Salenne&background=0ea5e9&color=fff"
    },
    {
        "handle": "@AurelienAutomatisation",
        "name": "Aurélien Fagioli",
        "id": "UCdL89Z0gQUDc1HT1882AGLw",
        "theme": "Agents & Automatisation",
        "avatar": "https://ui-avatars.com/api/?name=Aurelien+Fagioli&background=0ea5e9&color=fff"
    },
    {
        "handle": "@BaptIA",
        "name": "Baptiste Simard - IA",
        "id": "UCzabGLybo9x307MkDtqTyFQ",
        "theme": "Agents & Automatisation",
        "avatar": "https://ui-avatars.com/api/?name=Baptiste+Simard&background=0ea5e9&color=fff"
    },
    {
        "handle": "@LudovicNedelec",
        "name": "Ludovic Nédélec",
        "id": "UCMJ00y5KeFDKzYh9D6Lc41A",
        "theme": "Productivité & Second Cerveau",
        "avatar": "https://ui-avatars.com/api/?name=Ludovic+Nedelec&background=0ea5e9&color=fff"
    },
    {
        "handle": "@JonasEkanbo",
        "name": "Jonas Ekanbo",
        "id": "UCF2fb5WylqKbw0SgOlJKXMA",
        "theme": "Business & Monétisation IA",
        "avatar": "https://ui-avatars.com/api/?name=Jonas+Ekanbo&background=0ea5e9&color=fff"
    },
    {
        "handle": "@RenaudDekode",
        "name": "Renaud Dékode",
        "id": "UCOWu-2h4IpoEjhsRlTuesFg",
        "theme": "Actualités Tech",
        "avatar": "https://ui-avatars.com/api/?name=Renaud+Dekode&background=0ea5e9&color=fff"
    }
];

export const themes = [
    "Tous",
    "Agents & Automatisation",
    "Vibe Coding & Dev IA",
    "Outils & Modèles IA",
    "Business & Monétisation IA",
    "Productivité & Second Cerveau",
    "Actualités Tech"
];

export const allVideos = [
    {
        "id": "uqwsoIk6NhM",
        "videoId": "uqwsoIk6NhM",
        "title": "OpenClaw : l’IA devient collègue",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-09-03",
        "url": "https://www.youtube.com/watch?v=uqwsoIk6NhM",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : OpenClaw : l’IA devient collègue...",
        "duration": 131,
        "isShort": true
    },
    {
        "id": "9N13WjnNHfA",
        "videoId": "9N13WjnNHfA",
        "title": "10 choses à tester si tu paies Claude !",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-09-02",
        "url": "https://www.youtube.com/watch?v=9N13WjnNHfA",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : 10 choses à tester si tu paies Claude !...",
        "duration": 82,
        "isShort": true
    },
    {
        "id": "3LfqOETwkd0",
        "videoId": "3LfqOETwkd0",
        "title": "Le monopole de Nvidia est en train de tomber (actu IA)",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-09-02",
        "url": "https://www.youtube.com/watch?v=3LfqOETwkd0",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Le monopole de Nvidia est en train de tomber (actu IA)...",
        "duration": 1582,
        "isShort": false
    },
    {
        "id": "OIdKHTpDeVY",
        "videoId": "OIdKHTpDeVY",
        "title": "Claude Fable 5.1 le test ULTIME",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-09-02",
        "url": "https://www.youtube.com/watch?v=OIdKHTpDeVY",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Claude Fable 5.1 le test ULTIME...",
        "duration": 691,
        "isShort": false
    },
    {
        "id": "AOoLcEFDGDA",
        "videoId": "AOoLcEFDGDA",
        "title": "Apprendre 97% de CLAUDE en 27 minutes (Guide Débutant ULTIME)",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-09-02",
        "url": "https://www.youtube.com/watch?v=AOoLcEFDGDA",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Thomas Berton : Apprendre 97% de CLAUDE en 27 minutes (Guide Débutant ULTIME)...",
        "duration": 1634,
        "isShort": false
    },
    {
        "id": "3OE5jqFfQng",
        "videoId": "3OE5jqFfQng",
        "title": "Claude Fable : l’IA qui bosse seule",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-09-02",
        "url": "https://www.youtube.com/watch?v=3OE5jqFfQng",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : Claude Fable : l’IA qui bosse seule...",
        "duration": 162,
        "isShort": true
    },
    {
        "id": "HFBUqkAiJyM",
        "videoId": "HFBUqkAiJyM",
        "title": "Fable 5,1, OpenClaw 2, ChatGPT et Solaris : folle rentrée !",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-09-02",
        "url": "https://www.youtube.com/watch?v=HFBUqkAiJyM",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : Fable 5,1, OpenClaw 2, ChatGPT et Solaris : folle rentrée !...",
        "duration": 2660,
        "isShort": false
    },
    {
        "id": "aaOkBpiamjE",
        "videoId": "aaOkBpiamjE",
        "title": "Fable 5,1, OpenClaw 2, ChatGPT et Solaris : folle rentrée ! + Le médecin et l'IA",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-09-02",
        "url": "https://www.youtube.com/watch?v=aaOkBpiamjE",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : Fable 5,1, OpenClaw 2, ChatGPT et Solaris : folle rentrée ! + Le médecin et l'IA...",
        "duration": 10409,
        "isShort": false
    },
    {
        "id": "mG4C2RLMFZU",
        "videoId": "mG4C2RLMFZU",
        "title": "Piratage : Anthropic face aux majors",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-09-02",
        "url": "https://www.youtube.com/watch?v=mG4C2RLMFZU",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : Piratage : Anthropic face aux majors...",
        "duration": 168,
        "isShort": true
    },
    {
        "id": "Jmil2UxcrlY",
        "videoId": "Jmil2UxcrlY",
        "title": "Utiliser Google Gemini mieux que 99% des gens !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-09-01",
        "url": "https://www.youtube.com/watch?v=Jmil2UxcrlY",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Utiliser Google Gemini mieux que 99% des gens !...",
        "duration": 46,
        "isShort": true
    },
    {
        "id": "QwuhJjpM9CE",
        "videoId": "QwuhJjpM9CE",
        "title": "Qwen vient-il de dévoiler le futur des LLM ?",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-09-01",
        "url": "https://www.youtube.com/watch?v=QwuhJjpM9CE",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Qwen vient-il de dévoiler le futur des LLM ?...",
        "duration": 123,
        "isShort": true
    },
    {
        "id": "smOC-8aEe00",
        "videoId": "smOC-8aEe00",
        "title": "Un CRM open source a revendre aux entreprises",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-09-01",
        "url": "https://www.youtube.com/watch?v=smOC-8aEe00",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Un CRM open source a revendre aux entreprises...",
        "duration": 33,
        "isShort": true
    },
    {
        "id": "Gbk-v_fNRDk",
        "videoId": "Gbk-v_fNRDk",
        "title": "Bill Gates sonne l'alarme sur l'IA",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-09-01",
        "url": "https://www.youtube.com/watch?v=Gbk-v_fNRDk",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : Bill Gates sonne l'alarme sur l'IA...",
        "duration": 158,
        "isShort": true
    },
    {
        "id": "q2C_bC5Ee6M",
        "videoId": "q2C_bC5Ee6M",
        "title": "OpenAI débranche Cursor",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-09-01",
        "url": "https://www.youtube.com/watch?v=q2C_bC5Ee6M",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : OpenAI débranche Cursor...",
        "duration": 134,
        "isShort": true
    },
    {
        "id": "kSVNu76yxpc",
        "videoId": "kSVNu76yxpc",
        "title": "4 choses que je construirais dans Claude en un weekend",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-31",
        "url": "https://www.youtube.com/watch?v=kSVNu76yxpc",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : 4 choses que je construirais dans Claude en un weekend...",
        "duration": 37,
        "isShort": true
    },
    {
        "id": "pHRVMrxIxMQ",
        "videoId": "pHRVMrxIxMQ",
        "title": "Ma nouvelle vie à Hong Kong : je vous raconte tout",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-31",
        "url": "https://www.youtube.com/watch?v=pHRVMrxIxMQ",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Ma nouvelle vie à Hong Kong : je vous raconte tout...",
        "duration": 1455,
        "isShort": false
    },
    {
        "id": "0FlfKKNbK9E",
        "videoId": "0FlfKKNbK9E",
        "title": "Ce modèle gratuit vient de rattraper les géants de l’IA",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-31",
        "url": "https://www.youtube.com/watch?v=0FlfKKNbK9E",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Ce modèle gratuit vient de rattraper les géants de l’IA...",
        "duration": 541,
        "isShort": false
    },
    {
        "id": "mAuxe-BLLbo",
        "videoId": "mAuxe-BLLbo",
        "title": "Quel modele IA tourne sur ta machine ?",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-31",
        "url": "https://www.youtube.com/watch?v=mAuxe-BLLbo",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Quel modele IA tourne sur ta machine ?...",
        "duration": 37,
        "isShort": true
    },
    {
        "id": "dv4IV4KdgNI",
        "videoId": "dv4IV4KdgNI",
        "title": "Comment utiliser Canva IA 2.0 comme un pro",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-08-31",
        "url": "https://www.youtube.com/watch?v=dv4IV4KdgNI",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : Comment utiliser Canva IA 2.0 comme un pro...",
        "duration": 6615,
        "isShort": false
    },
    {
        "id": "uPCcmrAckwg",
        "videoId": "uPCcmrAckwg",
        "title": "Starlink : le plan pour l’abattre",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-08-31",
        "url": "https://www.youtube.com/watch?v=uPCcmrAckwg",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : Starlink : le plan pour l’abattre...",
        "duration": 127,
        "isShort": true
    },
    {
        "id": "xlYkSLoiIAk",
        "videoId": "xlYkSLoiIAk",
        "title": "Russie et Chine veulent détruire Starlink, c'est la guerre partout + La troisième voie de l'IA !",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-08-31",
        "url": "https://www.youtube.com/watch?v=xlYkSLoiIAk",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : Russie et Chine veulent détruire Starlink, c'est la guerre partout + La troisième voie de l'IA !...",
        "duration": 12404,
        "isShort": false
    },
    {
        "id": "7ydBmHCptys",
        "videoId": "7ydBmHCptys",
        "title": "La Russie et la Chine veulent détruire Starlink, c'est la guerre partout",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-08-31",
        "url": "https://www.youtube.com/watch?v=7ydBmHCptys",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : La Russie et la Chine veulent détruire Starlink, c'est la guerre partout...",
        "duration": 3081,
        "isShort": false
    },
    {
        "id": "nWhW2VsSGDU",
        "videoId": "nWhW2VsSGDU",
        "title": "Kyiv sort ses robots, l'ONU alerte",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-08-31",
        "url": "https://www.youtube.com/watch?v=nWhW2VsSGDU",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : Kyiv sort ses robots, l'ONU alerte...",
        "duration": 168,
        "isShort": true
    },
    {
        "id": "OsPRnH_vOTg",
        "videoId": "OsPRnH_vOTg",
        "title": "J'ai analysé 177k€ de services IA vendus : voici ce que les PME achètent vraiment en 2026",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-08-30",
        "url": "https://www.youtube.com/watch?v=OsPRnH_vOTg",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : J'ai analysé 177k€ de services IA vendus : voici ce que les PME achètent vraiment en 2026...",
        "duration": 1521,
        "isShort": false
    },
    {
        "id": "DggNOKLuniE",
        "videoId": "DggNOKLuniE",
        "title": "4 sites pour le Vibecoding !",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-30",
        "url": "https://www.youtube.com/watch?v=DggNOKLuniE",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : 4 sites pour le Vibecoding !...",
        "duration": 41,
        "isShort": true
    },
    {
        "id": "C1esYFoZXBE",
        "videoId": "C1esYFoZXBE",
        "title": "Utilisez mieux Google Gemini que 99% des gens ! (de débutant à PRO)",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-08-30",
        "url": "https://www.youtube.com/watch?v=C1esYFoZXBE",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Utilisez mieux Google Gemini que 99% des gens ! (de débutant à PRO)...",
        "duration": 1950,
        "isShort": false
    },
    {
        "id": "QCffQAhaPSE",
        "videoId": "QCffQAhaPSE",
        "title": "Comment l'IA est devenue plus chère que ceux qu'elle remplace",
        "author": "Yassine Sdiri",
        "source": "@yassine-sdiri",
        "date": "2026-08-30",
        "url": "https://www.youtube.com/watch?v=QCffQAhaPSE",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Yassine Sdiri : Comment l'IA est devenue plus chère que ceux qu'elle remplace...",
        "duration": 1095,
        "isShort": false
    },
    {
        "id": "3hRLAJ8xTsw",
        "videoId": "3hRLAJ8xTsw",
        "title": "Stripe rachète OpenRouter #actu",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-30",
        "url": "https://www.youtube.com/watch?v=3hRLAJ8xTsw",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Stripe rachète OpenRouter #actu...",
        "duration": 56,
        "isShort": true
    },
    {
        "id": "W2LfhDOjrL4",
        "videoId": "W2LfhDOjrL4",
        "title": "Code world model : Et si on s’était trompé sur les World️️ models",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-30",
        "url": "https://www.youtube.com/watch?v=W2LfhDOjrL4",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Code world model : Et si on s’était trompé sur les World️️ models...",
        "duration": 111,
        "isShort": true
    },
    {
        "id": "D7ehyxv3UeQ",
        "videoId": "D7ehyxv3UeQ",
        "title": "Chaque PDF que tu uploades dans Claude te coûte deux fois plus de tokens !",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-29",
        "url": "https://www.youtube.com/watch?v=D7ehyxv3UeQ",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : Chaque PDF que tu uploades dans Claude te coûte deux fois plus de tokens !...",
        "duration": 50,
        "isShort": true
    },
    {
        "id": "GcETuqiVIiY",
        "videoId": "GcETuqiVIiY",
        "title": "Le watermark de Claude sur les textes IA",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-29",
        "url": "https://www.youtube.com/watch?v=GcETuqiVIiY",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Le watermark de Claude sur les textes IA...",
        "duration": 77,
        "isShort": true
    },
    {
        "id": "XNWC3_W5T4k",
        "videoId": "XNWC3_W5T4k",
        "title": "Et si on s’était trompé sur les world models ? (Code word model)",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-29",
        "url": "https://www.youtube.com/watch?v=XNWC3_W5T4k",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Et si on s’était trompé sur les world models ? (Code word model)...",
        "duration": 483,
        "isShort": false
    },
    {
        "id": "Bpkeimq3AXg",
        "videoId": "Bpkeimq3AXg",
        "title": "Ta voix en texte, gratuitement",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-29",
        "url": "https://www.youtube.com/watch?v=Bpkeimq3AXg",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Ta voix en texte, gratuitement...",
        "duration": 72,
        "isShort": true
    },
    {
        "id": "OHlcxAhSY_E",
        "videoId": "OHlcxAhSY_E",
        "title": "Regarde cette vidéo si tu diriges un business",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-29",
        "url": "https://www.youtube.com/watch?v=OHlcxAhSY_E",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Thomas Berton : Regarde cette vidéo si tu diriges un business...",
        "duration": 321,
        "isShort": false
    },
    {
        "id": "bRBIaj7JrWQ",
        "videoId": "bRBIaj7JrWQ",
        "title": "L'IA chinoise tourne sans Nvidia",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-08-29",
        "url": "https://www.youtube.com/watch?v=bRBIaj7JrWQ",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : L'IA chinoise tourne sans Nvidia...",
        "duration": 145,
        "isShort": true
    },
    {
        "id": "GWzJzy2xeYI",
        "videoId": "GWzJzy2xeYI",
        "title": "Claude a changé, faut se mettre à jour",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-08-29",
        "url": "https://www.youtube.com/watch?v=GWzJzy2xeYI",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : Claude a changé, faut se mettre à jour...",
        "duration": 2923,
        "isShort": false
    },
    {
        "id": "pgz6FdH5qVw",
        "videoId": "pgz6FdH5qVw",
        "title": "Meta : 17 Mds pour ados accros",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-08-29",
        "url": "https://www.youtube.com/watch?v=pgz6FdH5qVw",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : Meta : 17 Mds pour ados accros...",
        "duration": 166,
        "isShort": true
    },
    {
        "id": "fDq1XbGJaHM",
        "videoId": "fDq1XbGJaHM",
        "title": "DeepSeek Harness + Ollama = Un Agent IA (LOCAL) 🤯",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-28",
        "url": "https://www.youtube.com/watch?v=fDq1XbGJaHM",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : DeepSeek Harness + Ollama = Un Agent IA (LOCAL) 🤯...",
        "duration": 394,
        "isShort": false
    },
    {
        "id": "H_BVqej1C90",
        "videoId": "H_BVqej1C90",
        "title": "Nvidia veut contrôler l’IA ouverte",
        "author": "Renaud Dékode",
        "source": "@RenaudDekode",
        "date": "2026-08-28",
        "url": "https://www.youtube.com/watch?v=H_BVqej1C90",
        "category": "Actualités Tech",
        "summary": "Nouveauté de Renaud Dékode : Nvidia veut contrôler l’IA ouverte...",
        "duration": 119,
        "isShort": true
    },
    {
        "id": "F2cI_H6_1yw",
        "videoId": "F2cI_H6_1yw",
        "title": "3 commandes ChatGPT pour des visuels produit professionnels",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-27",
        "url": "https://www.youtube.com/watch?v=F2cI_H6_1yw",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : 3 commandes ChatGPT pour des visuels produit professionnels...",
        "duration": 21,
        "isShort": true
    },
    {
        "id": "ib4Bc_kbzR0",
        "videoId": "ib4Bc_kbzR0",
        "title": "CLAUDE + SEEDANCE 2.5 : un site à 10 000 € en 10 min",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-27",
        "url": "https://www.youtube.com/watch?v=ib4Bc_kbzR0",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : CLAUDE + SEEDANCE 2.5 : un site à 10 000 € en 10 min...",
        "duration": 681,
        "isShort": false
    },
    {
        "id": "QxhOKugAa78",
        "videoId": "QxhOKugAa78",
        "title": "6 choses pour lesquelles tu paies encore et que Claude fait gratuitement !",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-27",
        "url": "https://www.youtube.com/watch?v=QxhOKugAa78",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : 6 choses pour lesquelles tu paies encore et que Claude fait gratuitement !...",
        "duration": 10,
        "isShort": true
    },
    {
        "id": "pS81YzrmEzA",
        "videoId": "pS81YzrmEzA",
        "title": "Ils quittent Google !",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-27",
        "url": "https://www.youtube.com/watch?v=pS81YzrmEzA",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Ils quittent Google !...",
        "duration": 80,
        "isShort": true
    },
    {
        "id": "9JapGVVBR6o",
        "videoId": "9JapGVVBR6o",
        "title": "Le watermarking de Claude expliqué simplement (actu IA)",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-27",
        "url": "https://www.youtube.com/watch?v=9JapGVVBR6o",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Le watermarking de Claude expliqué simplement (actu IA)...",
        "duration": 1519,
        "isShort": false
    },
    {
        "id": "S__8c_pqYpE",
        "videoId": "S__8c_pqYpE",
        "title": "Le vol de raisonnement des IA",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-27",
        "url": "https://www.youtube.com/watch?v=S__8c_pqYpE",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Le vol de raisonnement des IA...",
        "duration": 130,
        "isShort": true
    },
    {
        "id": "ooD-9cn4AbY",
        "videoId": "ooD-9cn4AbY",
        "title": "Créez Votre Site Web Shopify en 5 Minutes ! Stratégie Géniale #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-27",
        "url": "https://www.youtube.com/watch?v=ooD-9cn4AbY",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Thomas Berton : Créez Votre Site Web Shopify en 5 Minutes ! Stratégie Géniale #shorts...",
        "duration": 90,
        "isShort": true
    },
    {
        "id": "6sJmTbU8RFM",
        "videoId": "6sJmTbU8RFM",
        "title": "Un framework de développement argentique complet pour Claude !",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-26",
        "url": "https://www.youtube.com/watch?v=6sJmTbU8RFM",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : Un framework de développement argentique complet pour Claude !...",
        "duration": 59,
        "isShort": true
    },
    {
        "id": "kQON-pgK95Q",
        "videoId": "kQON-pgK95Q",
        "title": "La souveraineté IA selon Mistral #actu",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-26",
        "url": "https://www.youtube.com/watch?v=kQON-pgK95Q",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : La souveraineté IA selon Mistral #actu...",
        "duration": 83,
        "isShort": true
    },
    {
        "id": "K3HuspM1HmM",
        "videoId": "K3HuspM1HmM",
        "title": "La Faille Qui Permet de Voler le Raisonnement des IA",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-26",
        "url": "https://www.youtube.com/watch?v=K3HuspM1HmM",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : La Faille Qui Permet de Voler le Raisonnement des IA...",
        "duration": 799,
        "isShort": false
    },
    {
        "id": "MEmgn1bE3EM",
        "videoId": "MEmgn1bE3EM",
        "title": "L'auto-DM Instagram que les influenceurs revendent",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-26",
        "url": "https://www.youtube.com/watch?v=MEmgn1bE3EM",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : L'auto-DM Instagram que les influenceurs revendent...",
        "duration": 58,
        "isShort": true
    },
    {
        "id": "e4F-TUpZXzk",
        "videoId": "e4F-TUpZXzk",
        "title": "Créer Site Shopify Sans Code: IA Claude Code Révélé! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-26",
        "url": "https://www.youtube.com/watch?v=e4F-TUpZXzk",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Thomas Berton : Créer Site Shopify Sans Code: IA Claude Code Révélé! #shorts...",
        "duration": 153,
        "isShort": true
    },
    {
        "id": "-FqnIlznw_8",
        "videoId": "-FqnIlznw_8",
        "title": "Transforme n'importe quel livre en skill Claude Code.  Tu donnes le PDF a Claude Code, il en extrait",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-26",
        "url": "https://www.youtube.com/watch?v=-FqnIlznw_8",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Thomas Berton : Transforme n'importe quel livre en skill Claude Code.  Tu donnes le PDF a Claude Code, il en extrait...",
        "duration": 43,
        "isShort": true
    },
    {
        "id": "jj0FIAOKNhs",
        "videoId": "jj0FIAOKNhs",
        "title": "Je note les profils de personnes qui veulent vendre de l'IA !",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-25",
        "url": "https://www.youtube.com/watch?v=jj0FIAOKNhs",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : Je note les profils de personnes qui veulent vendre de l'IA !...",
        "duration": 50,
        "isShort": true
    },
    {
        "id": "dk4eorkkni8",
        "videoId": "dk4eorkkni8",
        "title": "Les réglages indispensables dans Claude !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-08-25",
        "url": "https://www.youtube.com/watch?v=dk4eorkkni8",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Les réglages indispensables dans Claude !...",
        "duration": 77,
        "isShort": true
    },
    {
        "id": "SNeiWlJqEIo",
        "videoId": "SNeiWlJqEIo",
        "title": "Grok Bot c’est quoi ? #actu",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-25",
        "url": "https://www.youtube.com/watch?v=SNeiWlJqEIo",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Grok Bot c’est quoi ? #actu...",
        "duration": 69,
        "isShort": true
    },
    {
        "id": "tm_QZ7iIGeg",
        "videoId": "tm_QZ7iIGeg",
        "title": "Comment Automatiser ses Montages Vidéo avec Claude (Guide Complet)",
        "author": "Lucas Reverdy",
        "source": "@reverdybusiness",
        "date": "2026-08-25",
        "url": "https://www.youtube.com/watch?v=tm_QZ7iIGeg",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Lucas Reverdy : Comment Automatiser ses Montages Vidéo avec Claude (Guide Complet)...",
        "duration": 853,
        "isShort": false
    },
    {
        "id": "fK8D3Bx96Iw",
        "videoId": "fK8D3Bx96Iw",
        "title": "Codex et Claude Code gratuits, sans abonnement",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-25",
        "url": "https://www.youtube.com/watch?v=fK8D3Bx96Iw",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Codex et Claude Code gratuits, sans abonnement...",
        "duration": 40,
        "isShort": true
    },
    {
        "id": "P8drExEL4Bk",
        "videoId": "P8drExEL4Bk",
        "title": "Claude IA: Crée des Images et Vidéos Magiques FACILEMENT! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-25",
        "url": "https://www.youtube.com/watch?v=P8drExEL4Bk",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Thomas Berton : Claude IA: Crée des Images et Vidéos Magiques FACILEMENT! #shorts...",
        "duration": 40,
        "isShort": true
    },
    {
        "id": "GWf9yeqxwjk",
        "videoId": "GWf9yeqxwjk",
        "title": "J'ai créé 30 posts VIRAUX et 1 BUSINESS en 1H (Claude + Higgsfield) !",
        "author": "Aurélien Fagioli",
        "source": "@AurelienAutomatisation",
        "date": "2026-08-25",
        "url": "https://www.youtube.com/watch?v=GWf9yeqxwjk",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Aurélien Fagioli : J'ai créé 30 posts VIRAUX et 1 BUSINESS en 1H (Claude + Higgsfield) !...",
        "duration": 3889,
        "isShort": false
    },
    {
        "id": "y2KpFbVVSQU",
        "videoId": "y2KpFbVVSQU",
        "title": "Le modèle open-source de Meta #actu",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-24",
        "url": "https://www.youtube.com/watch?v=y2KpFbVVSQU",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Le modèle open-source de Meta #actu...",
        "duration": 73,
        "isShort": true
    },
    {
        "id": "k0myRsQCsp0",
        "videoId": "k0myRsQCsp0",
        "title": "La fin des gros GPU ? (Diffusionblocks)",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-24",
        "url": "https://www.youtube.com/watch?v=k0myRsQCsp0",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : La fin des gros GPU ? (Diffusionblocks)...",
        "duration": 124,
        "isShort": true
    },
    {
        "id": "iTyl6yfb6Jo",
        "videoId": "iTyl6yfb6Jo",
        "title": "CapCut Pro gratuit et open source",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-24",
        "url": "https://www.youtube.com/watch?v=iTyl6yfb6Jo",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : CapCut Pro gratuit et open source...",
        "duration": 35,
        "isShort": true
    },
    {
        "id": "jzXGxXdjkTQ",
        "videoId": "jzXGxXdjkTQ",
        "title": "Produit Dynamique : Création Vidéo Style Balenciaga Facile #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-24",
        "url": "https://www.youtube.com/watch?v=jzXGxXdjkTQ",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Thomas Berton : Produit Dynamique : Création Vidéo Style Balenciaga Facile #shorts...",
        "duration": 69,
        "isShort": true
    },
    {
        "id": "N8e0LLHfTJY",
        "videoId": "N8e0LLHfTJY",
        "title": "La différence entre un Consultant IA à 0€ et un à 15k€/mois",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-08-23",
        "url": "https://www.youtube.com/watch?v=N8e0LLHfTJY",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : La différence entre un Consultant IA à 0€ et un à 15k€/mois...",
        "duration": 1577,
        "isShort": false
    },
    {
        "id": "8q8cWIY-FPI",
        "videoId": "8q8cWIY-FPI",
        "title": "Ce que personne ne te dit sur la sécurité de ton app !",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-23",
        "url": "https://www.youtube.com/watch?v=8q8cWIY-FPI",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : Ce que personne ne te dit sur la sécurité de ton app !...",
        "duration": 37,
        "isShort": true
    },
    {
        "id": "zfuvmmNuL7g",
        "videoId": "zfuvmmNuL7g",
        "title": "Voici les 2 outils que j’utilise pour créer tout mes workflows IA",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-23",
        "url": "https://www.youtube.com/watch?v=zfuvmmNuL7g",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : Voici les 2 outils que j’utilise pour créer tout mes workflows IA...",
        "duration": 87,
        "isShort": true
    },
    {
        "id": "REqJ7H7i2jQ",
        "videoId": "REqJ7H7i2jQ",
        "title": "12 IA de Google GRATUITES à Absolument Connaître en 2027",
        "author": "Yassine Sdiri",
        "source": "@yassine-sdiri",
        "date": "2026-08-23",
        "url": "https://www.youtube.com/watch?v=REqJ7H7i2jQ",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Yassine Sdiri : 12 IA de Google GRATUITES à Absolument Connaître en 2027...",
        "duration": 1297,
        "isShort": false
    },
    {
        "id": "UsLU-dkEg5M",
        "videoId": "UsLU-dkEg5M",
        "title": "DeepSeek Harness : la bombe est lâchée",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-23",
        "url": "https://www.youtube.com/watch?v=UsLU-dkEg5M",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : DeepSeek Harness : la bombe est lâchée...",
        "duration": 52,
        "isShort": true
    },
    {
        "id": "j5Cnwp2uOEw",
        "videoId": "j5Cnwp2uOEw",
        "title": "L’IA aurait dû tuer l’Eglise",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-23",
        "url": "https://www.youtube.com/watch?v=j5Cnwp2uOEw",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : L’IA aurait dû tuer l’Eglise...",
        "duration": 1303,
        "isShort": false
    },
    {
        "id": "l6WWP7arLEQ",
        "videoId": "l6WWP7arLEQ",
        "title": "Cette Découverte Pourrait Diviser la VRAM par 6 (DiffusionBlocks)",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-23",
        "url": "https://www.youtube.com/watch?v=l6WWP7arLEQ",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Cette Découverte Pourrait Diviser la VRAM par 6 (DiffusionBlocks)...",
        "duration": 518,
        "isShort": false
    },
    {
        "id": "lhodwaO1aGc",
        "videoId": "lhodwaO1aGc",
        "title": "DeepSeek Harness = Claude Code GRATUIT  🐳 (open source)",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-23",
        "url": "https://www.youtube.com/watch?v=lhodwaO1aGc",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : DeepSeek Harness = Claude Code GRATUIT  🐳 (open source)...",
        "duration": 775,
        "isShort": false
    },
    {
        "id": "A9eNMubDEm4",
        "videoId": "A9eNMubDEm4",
        "title": "5 prompts parfaits pour éviter que ton app se fasse hacker !",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-22",
        "url": "https://www.youtube.com/watch?v=A9eNMubDEm4",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : 5 prompts parfaits pour éviter que ton app se fasse hacker !...",
        "duration": 49,
        "isShort": true
    },
    {
        "id": "2Lq75AyVjdE",
        "videoId": "2Lq75AyVjdE",
        "title": "Transforme une video en site web anime",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-22",
        "url": "https://www.youtube.com/watch?v=2Lq75AyVjdE",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Transforme une video en site web anime...",
        "duration": 52,
        "isShort": true
    },
    {
        "id": "vy8keMoC_5c",
        "videoId": "vy8keMoC_5c",
        "title": "5 signes que tu sais vraiment utiliser l'IA !",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-21",
        "url": "https://www.youtube.com/watch?v=vy8keMoC_5c",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : 5 signes que tu sais vraiment utiliser l'IA !...",
        "duration": 42,
        "isShort": true
    },
    {
        "id": "2aHVkfXcpJA",
        "videoId": "2aHVkfXcpJA",
        "title": "Le seul dépôt Claude que tu as besoin !",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-21",
        "url": "https://www.youtube.com/watch?v=2aHVkfXcpJA",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : Le seul dépôt Claude que tu as besoin !...",
        "duration": 35,
        "isShort": true
    },
    {
        "id": "Od6j6r21FdE",
        "videoId": "Od6j6r21FdE",
        "title": "3 astuces pour des visuels IA de pro",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-21",
        "url": "https://www.youtube.com/watch?v=Od6j6r21FdE",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : 3 astuces pour des visuels IA de pro...",
        "duration": 84,
        "isShort": true
    },
    {
        "id": "o_k063WsJhE",
        "videoId": "o_k063WsJhE",
        "title": "5 plugins pour créer des sites web incroyables avec Claude !",
        "author": "Henri · ExplorIA",
        "source": "@HenriExplorIA",
        "date": "2026-08-20",
        "url": "https://www.youtube.com/watch?v=o_k063WsJhE",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Henri · ExplorIA : 5 plugins pour créer des sites web incroyables avec Claude !...",
        "duration": 70,
        "isShort": true
    },
    {
        "id": "uF3C3zQxZ-o",
        "videoId": "uF3C3zQxZ-o",
        "title": "C’est décidé, j'arrête Claude Code pour Codex !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-08-20",
        "url": "https://www.youtube.com/watch?v=uF3C3zQxZ-o",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : C’est décidé, j'arrête Claude Code pour Codex !...",
        "duration": 81,
        "isShort": true
    },
    {
        "id": "lNpseFbzM5Y",
        "videoId": "lNpseFbzM5Y",
        "title": "Deepseek Harness : La fin de Claude code ? 🤯",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-20",
        "url": "https://www.youtube.com/watch?v=lNpseFbzM5Y",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Deepseek Harness : La fin de Claude code ? 🤯...",
        "duration": 138,
        "isShort": true
    },
    {
        "id": "_EAfv6hGLcs",
        "videoId": "_EAfv6hGLcs",
        "title": "J'ai Automatisé 100% de mes Posts avec ce Script [GitHub]",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-20",
        "url": "https://www.youtube.com/watch?v=_EAfv6hGLcs",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : J'ai Automatisé 100% de mes Posts avec ce Script [GitHub]...",
        "duration": 1146,
        "isShort": false
    },
    {
        "id": "Kmlebm-Otp8",
        "videoId": "Kmlebm-Otp8",
        "title": "Claude Code + Shopify : Le combo pour créer des sites à 5 chiffres",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-20",
        "url": "https://www.youtube.com/watch?v=Kmlebm-Otp8",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Thomas Berton : Claude Code + Shopify : Le combo pour créer des sites à 5 chiffres...",
        "duration": 2188,
        "isShort": false
    },
    {
        "id": "Y-C_71H-mAg",
        "videoId": "Y-C_71H-mAg",
        "title": "Anthropic vient de lancer un avertissement pour les 6 à 12 prochains mois...",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-08-19",
        "url": "https://www.youtube.com/watch?v=Y-C_71H-mAg",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Anthropic vient de lancer un avertissement pour les 6 à 12 prochains mois......",
        "duration": 1418,
        "isShort": false
    },
    {
        "id": "VCntIHygMlg",
        "videoId": "VCntIHygMlg",
        "title": "DeepSeek lâche une bombe : DeepSeek Harness (actu IA)",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-19",
        "url": "https://www.youtube.com/watch?v=VCntIHygMlg",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : DeepSeek lâche une bombe : DeepSeek Harness (actu IA)...",
        "duration": 1247,
        "isShort": false
    },
    {
        "id": "OExbLboNEaw",
        "videoId": "OExbLboNEaw",
        "title": "DeepSeek Harness : La Fin de Claude Code ? (Installation + Test)",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-19",
        "url": "https://www.youtube.com/watch?v=OExbLboNEaw",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : DeepSeek Harness : La Fin de Claude Code ? (Installation + Test)...",
        "duration": 709,
        "isShort": false
    },
    {
        "id": "GwVB8H69_jE",
        "videoId": "GwVB8H69_jE",
        "title": "Un mec a open sourcé toutes les données de Wall Street",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-19",
        "url": "https://www.youtube.com/watch?v=GwVB8H69_jE",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Un mec a open sourcé toutes les données de Wall Street...",
        "duration": 39,
        "isShort": true
    },
    {
        "id": "E_vNH-XoXbQ",
        "videoId": "E_vNH-XoXbQ",
        "title": "Les hacks ultimes pour économiser vos tokens dans Claude !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-08-18",
        "url": "https://www.youtube.com/watch?v=E_vNH-XoXbQ",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Les hacks ultimes pour économiser vos tokens dans Claude !...",
        "duration": 104,
        "isShort": true
    },
    {
        "id": "89J8aJpzBLc",
        "videoId": "89J8aJpzBLc",
        "title": "Prédire les cyclones avec l’IA #actu",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-18",
        "url": "https://www.youtube.com/watch?v=89J8aJpzBLc",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Prédire les cyclones avec l’IA #actu...",
        "duration": 37,
        "isShort": true
    },
    {
        "id": "7PEBbSp9kws",
        "videoId": "7PEBbSp9kws",
        "title": "Muse Glimmer : le retour inattendu de Meta dans l’open source",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-18",
        "url": "https://www.youtube.com/watch?v=7PEBbSp9kws",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Muse Glimmer : le retour inattendu de Meta dans l’open source...",
        "duration": 416,
        "isShort": false
    },
    {
        "id": "4AjMSaNAI1w",
        "videoId": "4AjMSaNAI1w",
        "title": "Claude fait une découverte folle après 650 échecs",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-18",
        "url": "https://www.youtube.com/watch?v=4AjMSaNAI1w",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Claude fait une découverte folle après 650 échecs...",
        "duration": 132,
        "isShort": true
    },
    {
        "id": "riqjZ7H23Ys",
        "videoId": "riqjZ7H23Ys",
        "title": "Le robot qui fait ta valise #xiaomi",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-17",
        "url": "https://www.youtube.com/watch?v=riqjZ7H23Ys",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Le robot qui fait ta valise #xiaomi...",
        "duration": 60,
        "isShort": true
    },
    {
        "id": "aQ5Sa4OoOjA",
        "videoId": "aQ5Sa4OoOjA",
        "title": "650 échecs plus tard, Claude fait une découverte",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-17",
        "url": "https://www.youtube.com/watch?v=aQ5Sa4OoOjA",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : 650 échecs plus tard, Claude fait une découverte...",
        "duration": 350,
        "isShort": false
    },
    {
        "id": "a-bxMZnM-n0",
        "videoId": "a-bxMZnM-n0",
        "title": "Transforme n'importe quel livre en skill Claude Code",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-17",
        "url": "https://www.youtube.com/watch?v=a-bxMZnM-n0",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Transforme n'importe quel livre en skill Claude Code...",
        "duration": 35,
        "isShort": true
    },
    {
        "id": "tb-7zB5pwng",
        "videoId": "tb-7zB5pwng",
        "title": "Vous utilisez 10 % de Claude (voici les 90 % cachés)",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-08-17",
        "url": "https://www.youtube.com/watch?v=tb-7zB5pwng",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : Vous utilisez 10 % de Claude (voici les 90 % cachés)...",
        "duration": 1301,
        "isShort": false
    },
    {
        "id": "QbcPDv-s2-E",
        "videoId": "QbcPDv-s2-E",
        "title": "Comment Bâtir un Business en SOLO avec l’IA (grâce à Claude Code)",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-08-16",
        "url": "https://www.youtube.com/watch?v=QbcPDv-s2-E",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Comment Bâtir un Business en SOLO avec l’IA (grâce à Claude Code)...",
        "duration": 1345,
        "isShort": false
    },
    {
        "id": "6GuY15wy6DY",
        "videoId": "6GuY15wy6DY",
        "title": "Le problème de Claude Code",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-16",
        "url": "https://www.youtube.com/watch?v=6GuY15wy6DY",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Le problème de Claude Code...",
        "duration": 73,
        "isShort": true
    },
    {
        "id": "4rFx2B6UgiA",
        "videoId": "4rFx2B6UgiA",
        "title": "Ce repo open source découpe tes vidéos en shorts tout seul",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-16",
        "url": "https://www.youtube.com/watch?v=4rFx2B6UgiA",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Ce repo open source découpe tes vidéos en shorts tout seul...",
        "duration": 30,
        "isShort": true
    },
    {
        "id": "EGL2DQ1MJds",
        "videoId": "EGL2DQ1MJds",
        "title": "La nouvelle fonctionnalité incroyable de Claude !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-08-14",
        "url": "https://www.youtube.com/watch?v=EGL2DQ1MJds",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : La nouvelle fonctionnalité incroyable de Claude !...",
        "duration": 75,
        "isShort": true
    },
    {
        "id": "eRaek8u2CS8",
        "videoId": "eRaek8u2CS8",
        "title": "Commente Vocal pour avoir le prompt !",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-14",
        "url": "https://www.youtube.com/watch?v=eRaek8u2CS8",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Thomas Berton : Commente Vocal pour avoir le prompt !...",
        "duration": 33,
        "isShort": true
    },
    {
        "id": "odK-rqGSYR8",
        "videoId": "odK-rqGSYR8",
        "title": "Demandez à l'IA de poser des questions avant TOUT ! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-14",
        "url": "https://www.youtube.com/watch?v=odK-rqGSYR8",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Thomas Berton : Demandez à l'IA de poser des questions avant TOUT ! #shorts...",
        "duration": 56,
        "isShort": true
    },
    {
        "id": "gK1mBVZUlVQ",
        "videoId": "gK1mBVZUlVQ",
        "title": "Claude + DataForSEO : Le SEO Ne Sera Plus Jamais Pareil",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-13",
        "url": "https://www.youtube.com/watch?v=gK1mBVZUlVQ",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Claude + DataForSEO : Le SEO Ne Sera Plus Jamais Pareil...",
        "duration": 594,
        "isShort": false
    },
    {
        "id": "XgnYGTaPLws",
        "videoId": "XgnYGTaPLws",
        "title": "Longcat 2.0 : La fin des GPU NVIDIA ? 🇨🇳",
        "author": "Nerdy Kings",
        "source": "@NerdyKings",
        "date": "2026-08-13",
        "url": "https://www.youtube.com/watch?v=XgnYGTaPLws",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Nerdy Kings : Longcat 2.0 : La fin des GPU NVIDIA ? 🇨🇳...",
        "duration": 112,
        "isShort": true
    },
    {
        "id": "kHcqcR0lQz0",
        "videoId": "kHcqcR0lQz0",
        "title": "Sora : La Révolution Vidéo IA Qui Va Tout Changer ! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-13",
        "url": "https://www.youtube.com/watch?v=kHcqcR0lQz0",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Thomas Berton : Sora : La Révolution Vidéo IA Qui Va Tout Changer ! #shorts...",
        "duration": 26,
        "isShort": true
    },
    {
        "id": "CxDNjAIHSJc",
        "videoId": "CxDNjAIHSJc",
        "title": "Cloud Code: Prenez le contrôle TOTAL de votre ordinateur ! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-12",
        "url": "https://www.youtube.com/watch?v=CxDNjAIHSJc",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Thomas Berton : Cloud Code: Prenez le contrôle TOTAL de votre ordinateur ! #shorts...",
        "duration": 39,
        "isShort": true
    },
    {
        "id": "U-8CR0yIKy0",
        "videoId": "U-8CR0yIKy0",
        "title": "IA hors de contrôle: L'IA inscrite à un webinaire de 3900€ ! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-12",
        "url": "https://www.youtube.com/watch?v=U-8CR0yIKy0",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Thomas Berton : IA hors de contrôle: L'IA inscrite à un webinaire de 3900€ ! #shorts...",
        "duration": 34,
        "isShort": true
    },
    {
        "id": "lmU9IBKEUno",
        "videoId": "lmU9IBKEUno",
        "title": "Arrêtez d'utiliser Copilot sans connaître ces 7 astuces !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-08-11",
        "url": "https://www.youtube.com/watch?v=lmU9IBKEUno",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Arrêtez d'utiliser Copilot sans connaître ces 7 astuces !...",
        "duration": 29,
        "isShort": true
    },
    {
        "id": "LWvjJkLtDhQ",
        "videoId": "LWvjJkLtDhQ",
        "title": "AIOS: L'IA sécurisée, votre environnement isolé et protégé! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-11",
        "url": "https://www.youtube.com/watch?v=LWvjJkLtDhQ",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Thomas Berton : AIOS: L'IA sécurisée, votre environnement isolé et protégé! #shorts...",
        "duration": 61,
        "isShort": true
    },
    {
        "id": "fVtO2xdsvXU",
        "videoId": "fVtO2xdsvXU",
        "title": "Claude Code : Outils payants ? C'est terminé, c'est gratuit ! #shorts",
        "author": "Thomas Berton",
        "source": "@thomasbssh",
        "date": "2026-08-11",
        "url": "https://www.youtube.com/watch?v=fVtO2xdsvXU",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Thomas Berton : Claude Code : Outils payants ? C'est terminé, c'est gratuit ! #shorts...",
        "duration": 29,
        "isShort": true
    },
    {
        "id": "EQt4H1aDWBw",
        "videoId": "EQt4H1aDWBw",
        "title": "Des employés IA gratuits pour tous (merci le cofondateur de Twitter)",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-08-10",
        "url": "https://www.youtube.com/watch?v=EQt4H1aDWBw",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : Des employés IA gratuits pour tous (merci le cofondateur de Twitter)...",
        "duration": 1123,
        "isShort": false
    },
    {
        "id": "WFWNKIohrEc",
        "videoId": "WFWNKIohrEc",
        "title": "Dans les coulisses de mon Agence IA",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-08-09",
        "url": "https://www.youtube.com/watch?v=WFWNKIohrEc",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Dans les coulisses de mon Agence IA...",
        "duration": 1167,
        "isShort": false
    },
    {
        "id": "4km3oLGe-iQ",
        "videoId": "4km3oLGe-iQ",
        "title": "Personne ne réalise ce que le nouveau ChatGPT peut faire",
        "author": "Yassine Sdiri",
        "source": "@yassine-sdiri",
        "date": "2026-08-09",
        "url": "https://www.youtube.com/watch?v=4km3oLGe-iQ",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Yassine Sdiri : Personne ne réalise ce que le nouveau ChatGPT peut faire...",
        "duration": 1347,
        "isShort": false
    },
    {
        "id": "-TVOe0WqSro",
        "videoId": "-TVOe0WqSro",
        "title": "Comment créer un site web avec ChatGPT et Hostinger Horizon",
        "author": "Jonas Ekanbo",
        "source": "@JonasEkanbo",
        "date": "2026-08-09",
        "url": "https://www.youtube.com/watch?v=-TVOe0WqSro",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Jonas Ekanbo : Comment créer un site web avec ChatGPT et Hostinger Horizon...",
        "duration": 1497,
        "isShort": false
    },
    {
        "id": "xAlXes0E34k",
        "videoId": "xAlXes0E34k",
        "title": "Claude Design vient de sortir le Motion Design par IA",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-08-05",
        "url": "https://www.youtube.com/watch?v=xAlXes0E34k",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Claude Design vient de sortir le Motion Design par IA...",
        "duration": 1400,
        "isShort": false
    },
    {
        "id": "iWoTS-c6Fbg",
        "videoId": "iWoTS-c6Fbg",
        "title": "Créer ton Agent IA simplement ! (Sans coder)",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-08-05",
        "url": "https://www.youtube.com/watch?v=iWoTS-c6Fbg",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Créer ton Agent IA simplement ! (Sans coder)...",
        "duration": 42,
        "isShort": true
    },
    {
        "id": "im6rjBitL9M",
        "videoId": "im6rjBitL9M",
        "title": "Les 7 Hacks pour ne plus JAMAIS Atteindre la Limite de Claude",
        "author": "Lucas Reverdy",
        "source": "@reverdybusiness",
        "date": "2026-08-05",
        "url": "https://www.youtube.com/watch?v=im6rjBitL9M",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Lucas Reverdy : Les 7 Hacks pour ne plus JAMAIS Atteindre la Limite de Claude...",
        "duration": 688,
        "isShort": false
    },
    {
        "id": "rQuiE7S7Jzg",
        "videoId": "rQuiE7S7Jzg",
        "title": "Claude Skills : Tu peux enfin TOUT automatiser en montrant ton ÉCRAN !",
        "author": "Aurélien Fagioli",
        "source": "@AurelienAutomatisation",
        "date": "2026-08-05",
        "url": "https://www.youtube.com/watch?v=rQuiE7S7Jzg",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Aurélien Fagioli : Claude Skills : Tu peux enfin TOUT automatiser en montrant ton ÉCRAN !...",
        "duration": 653,
        "isShort": false
    },
    {
        "id": "eWN535AMIzQ",
        "videoId": "eWN535AMIzQ",
        "title": "Créer ton 1er Agent IA sans coder en 30 min ! (je te montre TOUT)",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-08-04",
        "url": "https://www.youtube.com/watch?v=eWN535AMIzQ",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Créer ton 1er Agent IA sans coder en 30 min ! (je te montre TOUT)...",
        "duration": 1813,
        "isShort": false
    },
    {
        "id": "fsw03ZXHJik",
        "videoId": "fsw03ZXHJik",
        "title": "Mistral sera bientôt partout (apprenez-le maintenant)",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-08-04",
        "url": "https://www.youtube.com/watch?v=fsw03ZXHJik",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : Mistral sera bientôt partout (apprenez-le maintenant)...",
        "duration": 1787,
        "isShort": false
    },
    {
        "id": "gBY3xIaDquY",
        "videoId": "gBY3xIaDquY",
        "title": "J'ai dépensé 50.000€ en moins d'1 an dans des formations (voici ce que j'ai appris)",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-08-02",
        "url": "https://www.youtube.com/watch?v=gBY3xIaDquY",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : J'ai dépensé 50.000€ en moins d'1 an dans des formations (voici ce que j'ai appris)...",
        "duration": 1552,
        "isShort": false
    },
    {
        "id": "Vv1eXHqOZlI",
        "videoId": "Vv1eXHqOZlI",
        "title": "Comment Vivre de l'IA en 2026 (sans compétence technique)",
        "author": "Yassine Sdiri",
        "source": "@yassine-sdiri",
        "date": "2026-08-02",
        "url": "https://www.youtube.com/watch?v=Vv1eXHqOZlI",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Yassine Sdiri : Comment Vivre de l'IA en 2026 (sans compétence technique)...",
        "duration": 2352,
        "isShort": false
    },
    {
        "id": "_-oxY6Q8BBs",
        "videoId": "_-oxY6Q8BBs",
        "title": "L'outil IA n°1 sur Github vient de RÉSOUDRE le problème de recherche sur Claude",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-07-29",
        "url": "https://www.youtube.com/watch?v=_-oxY6Q8BBs",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : L'outil IA n°1 sur Github vient de RÉSOUDRE le problème de recherche sur Claude...",
        "duration": 1079,
        "isShort": false
    },
    {
        "id": "-QWqZvcmNoY",
        "videoId": "-QWqZvcmNoY",
        "title": "Crée tes propres skills claude en t'enregistrant! 🎬",
        "author": "Julien Sanson",
        "source": "@JulienSnsn",
        "date": "2026-07-28",
        "url": "https://www.youtube.com/watch?v=-QWqZvcmNoY",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Julien Sanson : Crée tes propres skills claude en t'enregistrant! 🎬...",
        "duration": 136,
        "isShort": true
    },
    {
        "id": "IN_knFr6tQ4",
        "videoId": "IN_knFr6tQ4",
        "title": "Comment maîtriser l'IA mieux que 95% des business (5 secrets)",
        "author": "Yassine Sdiri",
        "source": "@yassine-sdiri",
        "date": "2026-07-27",
        "url": "https://www.youtube.com/watch?v=IN_knFr6tQ4",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Yassine Sdiri : Comment maîtriser l'IA mieux que 95% des business (5 secrets)...",
        "duration": 1022,
        "isShort": false
    },
    {
        "id": "flQLseCGsHU",
        "videoId": "flQLseCGsHU",
        "title": "Ce skill Claude va rendre ton IA humaine 👀",
        "author": "Julien Sanson",
        "source": "@JulienSnsn",
        "date": "2026-07-27",
        "url": "https://www.youtube.com/watch?v=flQLseCGsHU",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Julien Sanson : Ce skill Claude va rendre ton IA humaine 👀...",
        "duration": 57,
        "isShort": true
    },
    {
        "id": "pk-_1sanvCw",
        "videoId": "pk-_1sanvCw",
        "title": "J'ai créé mes propres applis avec Claude (et vous pouvez aussi)",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-07-27",
        "url": "https://www.youtube.com/watch?v=pk-_1sanvCw",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : J'ai créé mes propres applis avec Claude (et vous pouvez aussi)...",
        "duration": 913,
        "isShort": false
    },
    {
        "id": "de8Dp2EWo0g",
        "videoId": "de8Dp2EWo0g",
        "title": "J'ai analysé 85 Agences IA, voici ce qui marche en 2026",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-07-26",
        "url": "https://www.youtube.com/watch?v=de8Dp2EWo0g",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : J'ai analysé 85 Agences IA, voici ce qui marche en 2026...",
        "duration": 1322,
        "isShort": false
    },
    {
        "id": "dqGe3j8o-UM",
        "videoId": "dqGe3j8o-UM",
        "title": "Claude Code + Higgsfield créent vos pubs à votre place ! (marque, produits, UGC)",
        "author": "Julien Sanson",
        "source": "@JulienSnsn",
        "date": "2026-07-26",
        "url": "https://www.youtube.com/watch?v=dqGe3j8o-UM",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Julien Sanson : Claude Code + Higgsfield créent vos pubs à votre place ! (marque, produits, UGC)...",
        "duration": 1577,
        "isShort": false
    },
    {
        "id": "r6jn9iJJCfo",
        "videoId": "r6jn9iJJCfo",
        "title": "Opus 5 vient de tuer Fable (Vraiment)",
        "author": "Hugo Buisson",
        "source": "@Hugo_Buisson",
        "date": "2026-07-25",
        "url": "https://www.youtube.com/watch?v=r6jn9iJJCfo",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Hugo Buisson : Opus 5 vient de tuer Fable (Vraiment)...",
        "duration": 573,
        "isShort": false
    },
    {
        "id": "ZLw7kIgNcQE",
        "videoId": "ZLw7kIgNcQE",
        "title": "100 jours avec Hermes Agent résumé en 16 minutes",
        "author": "Hugo Buisson",
        "source": "@Hugo_Buisson",
        "date": "2026-07-24",
        "url": "https://www.youtube.com/watch?v=ZLw7kIgNcQE",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Hugo Buisson : 100 jours avec Hermes Agent résumé en 16 minutes...",
        "duration": 967,
        "isShort": false
    },
    {
        "id": "JIFgklJGj2w",
        "videoId": "JIFgklJGj2w",
        "title": "Arrêtez de créer des Agents IA, créez des Loops !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-07-23",
        "url": "https://www.youtube.com/watch?v=JIFgklJGj2w",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Arrêtez de créer des Agents IA, créez des Loops !...",
        "duration": 57,
        "isShort": true
    },
    {
        "id": "l1zVp3wOBSg",
        "videoId": "l1zVp3wOBSg",
        "title": "Gemini 3.6 Flash : Ne vous fiez pas aux Benchmarks",
        "author": "Hugo Buisson",
        "source": "@Hugo_Buisson",
        "date": "2026-07-23",
        "url": "https://www.youtube.com/watch?v=l1zVp3wOBSg",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Hugo Buisson : Gemini 3.6 Flash : Ne vous fiez pas aux Benchmarks...",
        "duration": 481,
        "isShort": false
    },
    {
        "id": "LGiaRxIsnzk",
        "videoId": "LGiaRxIsnzk",
        "title": "Il a fait son site SEUL avec CLAUDE CODE en 2 jours",
        "author": "Etienne Tillier",
        "source": "@EtienneTillierStudio",
        "date": "2026-07-22",
        "url": "https://www.youtube.com/watch?v=LGiaRxIsnzk",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Etienne Tillier : Il a fait son site SEUL avec CLAUDE CODE en 2 jours...",
        "duration": 3203,
        "isShort": false
    },
    {
        "id": "NQJPlvwVFOE",
        "videoId": "NQJPlvwVFOE",
        "title": "Comment Créer des Skills Claude comme un PRO (tuto complet)",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-07-22",
        "url": "https://www.youtube.com/watch?v=NQJPlvwVFOE",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Comment Créer des Skills Claude comme un PRO (tuto complet)...",
        "duration": 1659,
        "isShort": false
    },
    {
        "id": "FD0i-wFhnC4",
        "videoId": "FD0i-wFhnC4",
        "title": "Arrêtez les prompts. Passez aux Loops (Le futur des agents IA)",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-07-22",
        "url": "https://www.youtube.com/watch?v=FD0i-wFhnC4",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Arrêtez les prompts. Passez aux Loops (Le futur des agents IA)...",
        "duration": 2305,
        "isShort": false
    },
    {
        "id": "RutkqDcQZL0",
        "videoId": "RutkqDcQZL0",
        "title": "Comment utiliser Hermes GRATUITEMENT à VIE",
        "author": "Hugo Buisson",
        "source": "@Hugo_Buisson",
        "date": "2026-07-22",
        "url": "https://www.youtube.com/watch?v=RutkqDcQZL0",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Hugo Buisson : Comment utiliser Hermes GRATUITEMENT à VIE...",
        "duration": 620,
        "isShort": false
    },
    {
        "id": "F9YcVlyZahk",
        "videoId": "F9YcVlyZahk",
        "title": "Hermes V0.19 Vient De Révolutionner Les Agents IA - Voici pourquoi",
        "author": "Hugo Buisson",
        "source": "@Hugo_Buisson",
        "date": "2026-07-21",
        "url": "https://www.youtube.com/watch?v=F9YcVlyZahk",
        "category": "Outils & Modèles IA",
        "summary": "Nouveauté de Hugo Buisson : Hermes V0.19 Vient De Révolutionner Les Agents IA - Voici pourquoi...",
        "duration": 502,
        "isShort": false
    },
    {
        "id": "IziMU2lXstI",
        "videoId": "IziMU2lXstI",
        "title": "Ces 5 extensions rendent NotebookLM enfin complet",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-07-20",
        "url": "https://www.youtube.com/watch?v=IziMU2lXstI",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : Ces 5 extensions rendent NotebookLM enfin complet...",
        "duration": 1132,
        "isShort": false
    },
    {
        "id": "3q1slkjnJNE",
        "videoId": "3q1slkjnJNE",
        "title": "Comment je mène un Audit IA chez un client à 5M€ (extraits réels)",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-07-19",
        "url": "https://www.youtube.com/watch?v=3q1slkjnJNE",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Comment je mène un Audit IA chez un client à 5M€ (extraits réels)...",
        "duration": 1539,
        "isShort": false
    },
    {
        "id": "ocFNQTfj49U",
        "videoId": "ocFNQTfj49U",
        "title": "Deepseek a résolu le plus gros problème de l’IA",
        "author": "Yassine Sdiri",
        "source": "@yassine-sdiri",
        "date": "2026-07-19",
        "url": "https://www.youtube.com/watch?v=ocFNQTfj49U",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Yassine Sdiri : Deepseek a résolu le plus gros problème de l’IA...",
        "duration": 1010,
        "isShort": false
    },
    {
        "id": "cBH0KT9SG_c",
        "videoId": "cBH0KT9SG_c",
        "title": "La nouvelle fonctionnalité de n8n est INCROYABLE (mieux que Claude Code?)",
        "author": "Julien Sanson",
        "source": "@JulienSnsn",
        "date": "2026-07-19",
        "url": "https://www.youtube.com/watch?v=cBH0KT9SG_c",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Julien Sanson : La nouvelle fonctionnalité de n8n est INCROYABLE (mieux que Claude Code?)...",
        "duration": 1141,
        "isShort": false
    },
    {
        "id": "JnUPQ0lwgpI",
        "videoId": "JnUPQ0lwgpI",
        "title": "Voici Copilot Cowork, l'IA qui automatise vos tâches !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-07-16",
        "url": "https://www.youtube.com/watch?v=JnUPQ0lwgpI",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Voici Copilot Cowork, l'IA qui automatise vos tâches !...",
        "duration": 36,
        "isShort": true
    },
    {
        "id": "C9oGaD_L29M",
        "videoId": "C9oGaD_L29M",
        "title": "J'ai testé l’énorme mise à jour de ChatGPT ! (ChatGPT Work + GPT-5.6)",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-07-13",
        "url": "https://www.youtube.com/watch?v=C9oGaD_L29M",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : J'ai testé l’énorme mise à jour de ChatGPT ! (ChatGPT Work + GPT-5.6)...",
        "duration": 52,
        "isShort": true
    },
    {
        "id": "Sj3Z1-LO-I8",
        "videoId": "Sj3Z1-LO-I8",
        "title": "Mon système pour publier régulièrement avec 1 jour par semaine",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-07-13",
        "url": "https://www.youtube.com/watch?v=Sj3Z1-LO-I8",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : Mon système pour publier régulièrement avec 1 jour par semaine...",
        "duration": 646,
        "isShort": false
    },
    {
        "id": "rx7F_9Vm35Y",
        "videoId": "rx7F_9Vm35Y",
        "title": "ChatGPT travaille enfin à votre place ! (ChatGPT Work & GPT-5.6)",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-07-12",
        "url": "https://www.youtube.com/watch?v=rx7F_9Vm35Y",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : ChatGPT travaille enfin à votre place ! (ChatGPT Work & GPT-5.6)...",
        "duration": 1775,
        "isShort": false
    },
    {
        "id": "oU2slLP15VA",
        "videoId": "oU2slLP15VA",
        "title": "La nouvelle méthode pour utiliser Claude IA sans prompt",
        "author": "Yassine Sdiri",
        "source": "@yassine-sdiri",
        "date": "2026-07-12",
        "url": "https://www.youtube.com/watch?v=oU2slLP15VA",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Yassine Sdiri : La nouvelle méthode pour utiliser Claude IA sans prompt...",
        "duration": 805,
        "isShort": false
    },
    {
        "id": "5dF9rDlMGhE",
        "videoId": "5dF9rDlMGhE",
        "title": "Le nouveau ChatGPT est DISPO : voici tout ce qu’il peut faire.",
        "author": "Ludo Salenne",
        "source": "@LudovicSalenne",
        "date": "2026-07-09",
        "url": "https://www.youtube.com/watch?v=5dF9rDlMGhE",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Ludo Salenne : Le nouveau ChatGPT est DISPO : voici tout ce qu’il peut faire....",
        "duration": 2021,
        "isShort": false
    },
    {
        "id": "ReWSbxmIITM",
        "videoId": "ReWSbxmIITM",
        "title": "Comprendre le Fonctionnement des LLM : Guide Complet Débutant",
        "author": "Yassine Sdiri",
        "source": "@yassine-sdiri",
        "date": "2026-07-05",
        "url": "https://www.youtube.com/watch?v=ReWSbxmIITM",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Yassine Sdiri : Comprendre le Fonctionnement des LLM : Guide Complet Débutant...",
        "duration": 949,
        "isShort": false
    },
    {
        "id": "MEgLPh5FAqY",
        "videoId": "MEgLPh5FAqY",
        "title": "Les boucles d'agents IA : ce que personne te dit (et quand NE PAS en faire)",
        "author": "Julien Sanson",
        "source": "@JulienSnsn",
        "date": "2026-07-05",
        "url": "https://www.youtube.com/watch?v=MEgLPh5FAqY",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de Julien Sanson : Les boucles d'agents IA : ce que personne te dit (et quand NE PAS en faire)...",
        "duration": 1207,
        "isShort": false
    }
];
