// Fichier généré automatiquement le 2026-08-26T06:42:09.795Z
// Ne pas modifier manuellement

export const lastUpdate = "6:42:09 AM 8/26/2026";

export const sources = [
    {
        "handle": "@EtienneTillierStudio",
        "name": "Etienne Tillier",
        "id": "UCUlm3shqkgVNHLomYWZsfYA",
        "theme": "Vibe Coding & Dev IA",
        "avatar": "https://ui-avatars.com/api/?name=Etienne+Tillier&background=0ea5e9&color=fff"
    },
    {
        "handle": "@Simon_bcome",
        "name": "Simon Music",
        "id": "UCaryUIRfj7KAikH_ogrOzig",
        "theme": "Business & Monétisation IA",
        "avatar": "https://ui-avatars.com/api/?name=Simon+Music&background=0ea5e9&color=fff"
    },
    {
        "handle": "@HenriExplorIA",
        "name": "Henri · ExplorIA",
        "id": "UCxx03UqvjTy9w8iomLwTSuQ",
        "theme": "Outils & Modèles IA",
        "avatar": "https://ui-avatars.com/api/?name=Henri+ExplorIA&background=0ea5e9&color=fff"
    },
    {
        "handle": "@elliottpierret",
        "name": "Elliott Pierret",
        "id": "UCnJAGhDDEPdvY2g4ipf9PMQ",
        "theme": "Vibe Coding & Dev IA",
        "avatar": "https://ui-avatars.com/api/?name=Elliott+Pierret&background=0ea5e9&color=fff"
    },
    {
        "handle": "@ousmanedf",
        "name": "Ousmane Automatise",
        "id": "UC1o5Eo5Qf12_f6D836PsoPw",
        "theme": "Agents & Automatisation",
        "avatar": "https://ui-avatars.com/api/?name=Ousmane+Automatise&background=0ea5e9&color=fff"
    },
    {
        "handle": "@yassine-sdiri",
        "name": "Yassine Sdiri",
        "id": "UC94UeaPuTt_L51RkDxj9d_w",
        "theme": "Business & Monétisation IA",
        "avatar": "https://ui-avatars.com/api/?name=Yassine+Sdiri&background=0ea5e9&color=fff"
    },
    {
        "handle": "@cedric_effi10",
        "name": "Cédric Girard",
        "id": "UCjhLy8XRh4Q0NM2CD6pFPYQ",
        "theme": "Outils & Modèles IA",
        "avatar": "https://ui-avatars.com/api/?name=Cedric+Girard&background=0ea5e9&color=fff"
    },
    {
        "handle": "@EliottMeunier",
        "name": "Eliott Meunier",
        "id": "UCPo1nFSGNkyzrA9yvtkEvIw",
        "theme": "Productivité & Second Cerveau",
        "avatar": "https://ui-avatars.com/api/?name=Eliott+Meunier&background=0ea5e9&color=fff"
    },
    {
        "handle": "@reverdybusiness",
        "name": "Lucas Reverdy",
        "id": "UCabbBG5KYGtdTibrl_XHLOw",
        "theme": "Business & Monétisation IA",
        "avatar": "https://ui-avatars.com/api/?name=Lucas+Reverdy&background=0ea5e9&color=fff"
    },
    {
        "handle": "@JulienSnsn",
        "name": "Julien Sanson",
        "id": "UCK85rF_WKv1N6ojTzVbj3yw",
        "theme": "Agents & Automatisation",
        "avatar": "https://ui-avatars.com/api/?name=Julien+Sanson&background=0ea5e9&color=fff"
    },
    {
        "handle": "@NerdyKings",
        "name": "Nerdy Kings",
        "id": "UCp7vimq7dYKiVAJLPyI0GcA",
        "theme": "Outils & Modèles IA",
        "avatar": "https://ui-avatars.com/api/?name=Nerdy+Kings&background=0ea5e9&color=fff"
    },
    {
        "handle": "@iAlan_automatise",
        "name": "iAlan",
        "id": "UCdROsT8FZ2pacpipymmmaPw",
        "theme": "Agents & Automatisation",
        "avatar": "https://ui-avatars.com/api/?name=iAlan&background=0ea5e9&color=fff"
    },
    {
        "handle": "@LouisGraffeuil",
        "name": "Louis Graffeuil",
        "id": "UChkCdoCUCNYizE8d9TXsi4A",
        "theme": "Vibe Coding & Dev IA",
        "avatar": "https://ui-avatars.com/api/?name=Louis+Graffeuil&background=0ea5e9&color=fff"
    },
    {
        "handle": "@Hugo_Buisson",
        "name": "Hugo Buisson",
        "id": "UCeZvp_y5meYlfcGCFhl6UJQ",
        "theme": "Outils & Modèles IA",
        "avatar": "https://ui-avatars.com/api/?name=Hugo+Buisson&background=0ea5e9&color=fff"
    },
    {
        "handle": "@audelalia",
        "name": "Au-delà l'IA",
        "id": "UCNSPV84q4QlUtle6MS_7v1Q",
        "theme": "Productivité & Second Cerveau",
        "avatar": "https://ui-avatars.com/api/?name=Au+dela+l+IA&background=0ea5e9&color=fff"
    },
    {
        "handle": "@thomasbssh",
        "name": "Thomas Berton",
        "id": "UCxOWUTmenPJj5V6_g2-CS1g",
        "theme": "Agents & Automatisation",
        "avatar": "https://ui-avatars.com/api/?name=Thomas+Berton&background=0ea5e9&color=fff"
    },
    {
        "handle": "@LudovicSalenne",
        "name": "Ludo Salenne",
        "id": "UCnnYqSNKKygemgmxC9PyLTw",
        "theme": "Agents & Automatisation",
        "avatar": "https://ui-avatars.com/api/?name=Ludo+Salenne&background=0ea5e9&color=fff"
    },
    {
        "handle": "@AurelienAutomatisation",
        "name": "Aurélien Fagioli",
        "id": "UCdL89Z0gQUDc1HT1882AGLw",
        "theme": "Agents & Automatisation",
        "avatar": "https://ui-avatars.com/api/?name=Aurelien+Fagioli&background=0ea5e9&color=fff"
    },
    {
        "handle": "@BaptIA",
        "name": "Baptiste Simard - IA",
        "id": "UCzabGLybo9x307MkDtqTyFQ",
        "theme": "Agents & Automatisation",
        "avatar": "https://ui-avatars.com/api/?name=Baptiste+Simard&background=0ea5e9&color=fff"
    },
    {
        "handle": "@LudovicNedelec",
        "name": "Ludovic Nédélec",
        "id": "UCMJ00y5KeFDKzYh9D6Lc41A",
        "theme": "Productivité & Second Cerveau",
        "avatar": "https://ui-avatars.com/api/?name=Ludovic+Nedelec&background=0ea5e9&color=fff"
    },
    {
        "handle": "@JonasEkanbo",
        "name": "Jonas Ekanbo",
        "id": "UCF2fb5WylqKbw0SgOlJKXMA",
        "theme": "Business & Monétisation IA",
        "avatar": "https://ui-avatars.com/api/?name=Jonas+Ekanbo&background=0ea5e9&color=fff"
    },
    {
        "handle": "@RenaudDekode",
        "name": "Renaud Dékode",
        "id": "UCOWu-2h4IpoEjhsRlTuesFg",
        "theme": "Actualités Tech",
        "avatar": "https://ui-avatars.com/api/?name=Renaud+Dekode&background=0ea5e9&color=fff"
    }
];

export const themes = [
    "Tous",
    "Agents & Automatisation",
    "Vibe Coding & Dev IA",
    "Outils & Modèles IA",
    "Business & Monétisation IA",
    "Productivité & Second Cerveau",
    "Actualités Tech"
];

export const allVideos = [
    {
        "id": "dk4eorkkni8",
        "videoId": "dk4eorkkni8",
        "title": "Les réglages indispensables dans Claude !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-08-25",
        "url": "https://www.youtube.com/watch?v=dk4eorkkni8",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Les réglages indispensables dans Claude !...",
        "isShort": false
    },
    {
        "id": "SNeiWlJqEIo",
        "videoId": "SNeiWlJqEIo",
        "title": "Grok Bot c’est quoi ? #actu",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-25",
        "url": "https://www.youtube.com/watch?v=SNeiWlJqEIo",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Grok Bot c’est quoi ? #actu...",
        "isShort": false
    },
    {
        "id": "tm_QZ7iIGeg",
        "videoId": "tm_QZ7iIGeg",
        "title": "Comment Automatiser ses Montages Vidéo avec Claude (Guide Complet)",
        "author": "Lucas Reverdy",
        "source": "@reverdybusiness",
        "date": "2026-08-25",
        "url": "https://www.youtube.com/watch?v=tm_QZ7iIGeg",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Lucas Reverdy : Comment Automatiser ses Montages Vidéo avec Claude (Guide Complet)...",
        "isShort": false
    },
    {
        "id": "fK8D3Bx96Iw",
        "videoId": "fK8D3Bx96Iw",
        "title": "Codex et Claude Code gratuits, sans abonnement",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-25",
        "url": "https://www.youtube.com/watch?v=fK8D3Bx96Iw",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Codex et Claude Code gratuits, sans abonnement...",
        "isShort": false
    },
    {
        "id": "y2KpFbVVSQU",
        "videoId": "y2KpFbVVSQU",
        "title": "Le modèle open-source de Meta #actu",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-24",
        "url": "https://www.youtube.com/watch?v=y2KpFbVVSQU",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Le modèle open-source de Meta #actu...",
        "isShort": false
    },
    {
        "id": "iTyl6yfb6Jo",
        "videoId": "iTyl6yfb6Jo",
        "title": "CapCut Pro gratuit et open source",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-24",
        "url": "https://www.youtube.com/watch?v=iTyl6yfb6Jo",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : CapCut Pro gratuit et open source...",
        "isShort": false
    },
    {
        "id": "N8e0LLHfTJY",
        "videoId": "N8e0LLHfTJY",
        "title": "La différence entre un Consultant IA à 0€ et un à 15k€/mois",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-08-23",
        "url": "https://www.youtube.com/watch?v=N8e0LLHfTJY",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : La différence entre un Consultant IA à 0€ et un à 15k€/mois...",
        "isShort": false
    },
    {
        "id": "UsLU-dkEg5M",
        "videoId": "UsLU-dkEg5M",
        "title": "DeepSeek Harness : la bombe est lâchée",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-23",
        "url": "https://www.youtube.com/watch?v=UsLU-dkEg5M",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : DeepSeek Harness : la bombe est lâchée...",
        "isShort": false
    },
    {
        "id": "j5Cnwp2uOEw",
        "videoId": "j5Cnwp2uOEw",
        "title": "L’IA aurait dû tuer l’Eglise",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-23",
        "url": "https://www.youtube.com/watch?v=j5Cnwp2uOEw",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : L’IA aurait dû tuer l’Eglise...",
        "isShort": false
    },
    {
        "id": "lhodwaO1aGc",
        "videoId": "lhodwaO1aGc",
        "title": "DeepSeek Harness = Claude Code GRATUIT  🐳 (open source)",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-23",
        "url": "https://www.youtube.com/watch?v=lhodwaO1aGc",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : DeepSeek Harness = Claude Code GRATUIT  🐳 (open source)...",
        "isShort": false
    },
    {
        "id": "2Lq75AyVjdE",
        "videoId": "2Lq75AyVjdE",
        "title": "Transforme une video en site web anime",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-22",
        "url": "https://www.youtube.com/watch?v=2Lq75AyVjdE",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Transforme une video en site web anime...",
        "isShort": false
    },
    {
        "id": "Od6j6r21FdE",
        "videoId": "Od6j6r21FdE",
        "title": "3 astuces pour des visuels IA de pro",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-21",
        "url": "https://www.youtube.com/watch?v=Od6j6r21FdE",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : 3 astuces pour des visuels IA de pro...",
        "isShort": false
    },
    {
        "id": "uF3C3zQxZ-o",
        "videoId": "uF3C3zQxZ-o",
        "title": "C’est décidé, j'arrête Claude Code pour Codex !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-08-20",
        "url": "https://www.youtube.com/watch?v=uF3C3zQxZ-o",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : C’est décidé, j'arrête Claude Code pour Codex !...",
        "isShort": false
    },
    {
        "id": "_EAfv6hGLcs",
        "videoId": "_EAfv6hGLcs",
        "title": "J'ai Automatisé 100% de mes Posts avec ce Script [GitHub]",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-20",
        "url": "https://www.youtube.com/watch?v=_EAfv6hGLcs",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : J'ai Automatisé 100% de mes Posts avec ce Script [GitHub]...",
        "isShort": false
    },
    {
        "id": "Y-C_71H-mAg",
        "videoId": "Y-C_71H-mAg",
        "title": "Anthropic vient de lancer un avertissement pour les 6 à 12 prochains mois...",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-08-19",
        "url": "https://www.youtube.com/watch?v=Y-C_71H-mAg",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Anthropic vient de lancer un avertissement pour les 6 à 12 prochains mois......",
        "isShort": false
    },
    {
        "id": "VCntIHygMlg",
        "videoId": "VCntIHygMlg",
        "title": "DeepSeek lâche une bombe : DeepSeek Harness (actu IA)",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-19",
        "url": "https://www.youtube.com/watch?v=VCntIHygMlg",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : DeepSeek lâche une bombe : DeepSeek Harness (actu IA)...",
        "isShort": false
    },
    {
        "id": "GwVB8H69_jE",
        "videoId": "GwVB8H69_jE",
        "title": "Un mec a open sourcé toutes les données de Wall Street",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-19",
        "url": "https://www.youtube.com/watch?v=GwVB8H69_jE",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Un mec a open sourcé toutes les données de Wall Street...",
        "isShort": false
    },
    {
        "id": "E_vNH-XoXbQ",
        "videoId": "E_vNH-XoXbQ",
        "title": "Les hacks ultimes pour économiser vos tokens dans Claude !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-08-18",
        "url": "https://www.youtube.com/watch?v=E_vNH-XoXbQ",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Les hacks ultimes pour économiser vos tokens dans Claude !...",
        "isShort": false
    },
    {
        "id": "89J8aJpzBLc",
        "videoId": "89J8aJpzBLc",
        "title": "Prédire les cyclones avec l’IA #actu",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-18",
        "url": "https://www.youtube.com/watch?v=89J8aJpzBLc",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Prédire les cyclones avec l’IA #actu...",
        "isShort": false
    },
    {
        "id": "riqjZ7H23Ys",
        "videoId": "riqjZ7H23Ys",
        "title": "Le robot qui fait ta valise #xiaomi",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-17",
        "url": "https://www.youtube.com/watch?v=riqjZ7H23Ys",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Le robot qui fait ta valise #xiaomi...",
        "isShort": false
    },
    {
        "id": "a-bxMZnM-n0",
        "videoId": "a-bxMZnM-n0",
        "title": "Transforme n'importe quel livre en skill Claude Code",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-17",
        "url": "https://www.youtube.com/watch?v=a-bxMZnM-n0",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Transforme n'importe quel livre en skill Claude Code...",
        "isShort": false
    },
    {
        "id": "tb-7zB5pwng",
        "videoId": "tb-7zB5pwng",
        "title": "Vous utilisez 10 % de Claude (voici les 90 % cachés)",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-08-17",
        "url": "https://www.youtube.com/watch?v=tb-7zB5pwng",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : Vous utilisez 10 % de Claude (voici les 90 % cachés)...",
        "isShort": false
    },
    {
        "id": "QbcPDv-s2-E",
        "videoId": "QbcPDv-s2-E",
        "title": "Comment Bâtir un Business en SOLO avec l’IA (grâce à Claude Code)",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-08-16",
        "url": "https://www.youtube.com/watch?v=QbcPDv-s2-E",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Comment Bâtir un Business en SOLO avec l’IA (grâce à Claude Code)...",
        "isShort": false
    },
    {
        "id": "6GuY15wy6DY",
        "videoId": "6GuY15wy6DY",
        "title": "Le problème de Claude Code",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-16",
        "url": "https://www.youtube.com/watch?v=6GuY15wy6DY",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Le problème de Claude Code...",
        "isShort": false
    },
    {
        "id": "4rFx2B6UgiA",
        "videoId": "4rFx2B6UgiA",
        "title": "Ce repo open source découpe tes vidéos en shorts tout seul",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-16",
        "url": "https://www.youtube.com/watch?v=4rFx2B6UgiA",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Ce repo open source découpe tes vidéos en shorts tout seul...",
        "isShort": false
    },
    {
        "id": "dDMxmwIGYoQ",
        "videoId": "dDMxmwIGYoQ",
        "title": "Le World Mental Modeling",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-15",
        "url": "https://www.youtube.com/watch?v=dDMxmwIGYoQ",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Le World Mental Modeling...",
        "isShort": false
    },
    {
        "id": "EGL2DQ1MJds",
        "videoId": "EGL2DQ1MJds",
        "title": "La nouvelle fonctionnalité incroyable de Claude !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-08-14",
        "url": "https://www.youtube.com/watch?v=EGL2DQ1MJds",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : La nouvelle fonctionnalité incroyable de Claude !...",
        "duration": 75,
        "isShort": true
    },
    {
        "id": "Q2Aeg6AErAM",
        "videoId": "Q2Aeg6AErAM",
        "title": "Alibaba s’ouvre enfin !",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-14",
        "url": "https://www.youtube.com/watch?v=Q2Aeg6AErAM",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Alibaba s’ouvre enfin !...",
        "isShort": false
    },
    {
        "id": "wyI8RKwI8po",
        "videoId": "wyI8RKwI8po",
        "title": "Récupère tous les leads d'Internet en langage naturel",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-14",
        "url": "https://www.youtube.com/watch?v=wyI8RKwI8po",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Récupère tous les leads d'Internet en langage naturel...",
        "isShort": false
    },
    {
        "id": "P-nOn0R2hdI",
        "videoId": "P-nOn0R2hdI",
        "title": "Je te fais gagner 72 h de Seedance 2.5",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-13",
        "url": "https://www.youtube.com/watch?v=P-nOn0R2hdI",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Je te fais gagner 72 h de Seedance 2.5...",
        "isShort": false
    },
    {
        "id": "CQGNFHJ8xS8",
        "videoId": "CQGNFHJ8xS8",
        "title": "Ce retournement d’Alibaba en dit long sur l’IA (actu IA)",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-12",
        "url": "https://www.youtube.com/watch?v=CQGNFHJ8xS8",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Ce retournement d’Alibaba en dit long sur l’IA (actu IA)...",
        "isShort": false
    },
    {
        "id": "7ieeYRie5po",
        "videoId": "7ieeYRie5po",
        "title": "La sortie de Seedance 2.5 #actu",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-12",
        "url": "https://www.youtube.com/watch?v=7ieeYRie5po",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : La sortie de Seedance 2.5 #actu...",
        "isShort": false
    },
    {
        "id": "BRmdqp9QIto",
        "videoId": "BRmdqp9QIto",
        "title": "Seedance 2.5 : Miracle ou Arnaque ? (crash test)",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-12",
        "url": "https://www.youtube.com/watch?v=BRmdqp9QIto",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Seedance 2.5 : Miracle ou Arnaque ? (crash test)...",
        "isShort": false
    },
    {
        "id": "lmU9IBKEUno",
        "videoId": "lmU9IBKEUno",
        "title": "Arrêtez d'utiliser Copilot sans connaître ces 7 astuces !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-08-11",
        "url": "https://www.youtube.com/watch?v=lmU9IBKEUno",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Arrêtez d'utiliser Copilot sans connaître ces 7 astuces !...",
        "duration": 29,
        "isShort": true
    },
    {
        "id": "FK689G6PZsI",
        "videoId": "FK689G6PZsI",
        "title": "L’IA vidéo de Netflix #actu",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-11",
        "url": "https://www.youtube.com/watch?v=FK689G6PZsI",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : L’IA vidéo de Netflix #actu...",
        "isShort": false
    },
    {
        "id": "2pdYzn4BmM4",
        "videoId": "2pdYzn4BmM4",
        "title": "Ta voix en local, gratuite et open source",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-11",
        "url": "https://www.youtube.com/watch?v=2pdYzn4BmM4",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Ta voix en local, gratuite et open source...",
        "isShort": false
    },
    {
        "id": "tHEWNkr87eo",
        "videoId": "tHEWNkr87eo",
        "title": "Générer une vidéo avec du son stéréo natif #actu",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-10",
        "url": "https://www.youtube.com/watch?v=tHEWNkr87eo",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Générer une vidéo avec du son stéréo natif #actu...",
        "isShort": false
    },
    {
        "id": "lQX95S48FX0",
        "videoId": "lQX95S48FX0",
        "title": "Tes posts partent tout seuls",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-10",
        "url": "https://www.youtube.com/watch?v=lQX95S48FX0",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Tes posts partent tout seuls...",
        "isShort": false
    },
    {
        "id": "EQt4H1aDWBw",
        "videoId": "EQt4H1aDWBw",
        "title": "Des employés IA gratuits pour tous (merci le cofondateur de Twitter)",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-08-10",
        "url": "https://www.youtube.com/watch?v=EQt4H1aDWBw",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : Des employés IA gratuits pour tous (merci le cofondateur de Twitter)...",
        "duration": 1123,
        "isShort": false
    },
    {
        "id": "WFWNKIohrEc",
        "videoId": "WFWNKIohrEc",
        "title": "Dans les coulisses de mon Agence IA",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-08-09",
        "url": "https://www.youtube.com/watch?v=WFWNKIohrEc",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Dans les coulisses de mon Agence IA...",
        "isShort": false
    },
    {
        "id": "ni8BUQYm_QA",
        "videoId": "ni8BUQYm_QA",
        "title": "Nouveau modèle DeepSeek V4 Flash #actu",
        "author": "Eliott Meunier",
        "source": "@EliottMeunier",
        "date": "2026-08-09",
        "url": "https://www.youtube.com/watch?v=ni8BUQYm_QA",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Eliott Meunier : Nouveau modèle DeepSeek V4 Flash #actu...",
        "isShort": false
    },
    {
        "id": "39jsTqXYWCY",
        "videoId": "39jsTqXYWCY",
        "title": "Open source chinois ou modele ferme ?",
        "author": "iAlan",
        "source": "@iAlan_automatise",
        "date": "2026-08-09",
        "url": "https://www.youtube.com/watch?v=39jsTqXYWCY",
        "category": "Agents & Automatisation",
        "summary": "Nouveauté de iAlan : Open source chinois ou modele ferme ?...",
        "isShort": false
    },
    {
        "id": "xAlXes0E34k",
        "videoId": "xAlXes0E34k",
        "title": "Claude Design vient de sortir le Motion Design par IA",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-08-05",
        "url": "https://www.youtube.com/watch?v=xAlXes0E34k",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Claude Design vient de sortir le Motion Design par IA...",
        "isShort": false
    },
    {
        "id": "iWoTS-c6Fbg",
        "videoId": "iWoTS-c6Fbg",
        "title": "Créer ton Agent IA simplement ! (Sans coder)",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-08-05",
        "url": "https://www.youtube.com/watch?v=iWoTS-c6Fbg",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Créer ton Agent IA simplement ! (Sans coder)...",
        "duration": 42,
        "isShort": true
    },
    {
        "id": "im6rjBitL9M",
        "videoId": "im6rjBitL9M",
        "title": "Les 7 Hacks pour ne plus JAMAIS Atteindre la Limite de Claude",
        "author": "Lucas Reverdy",
        "source": "@reverdybusiness",
        "date": "2026-08-05",
        "url": "https://www.youtube.com/watch?v=im6rjBitL9M",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Lucas Reverdy : Les 7 Hacks pour ne plus JAMAIS Atteindre la Limite de Claude...",
        "duration": 688,
        "isShort": false
    },
    {
        "id": "eWN535AMIzQ",
        "videoId": "eWN535AMIzQ",
        "title": "Créer ton 1er Agent IA sans coder en 30 min ! (je te montre TOUT)",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-08-04",
        "url": "https://www.youtube.com/watch?v=eWN535AMIzQ",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Créer ton 1er Agent IA sans coder en 30 min ! (je te montre TOUT)...",
        "duration": 1813,
        "isShort": false
    },
    {
        "id": "fsw03ZXHJik",
        "videoId": "fsw03ZXHJik",
        "title": "Mistral sera bientôt partout (apprenez-le maintenant)",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-08-04",
        "url": "https://www.youtube.com/watch?v=fsw03ZXHJik",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : Mistral sera bientôt partout (apprenez-le maintenant)...",
        "duration": 1787,
        "isShort": false
    },
    {
        "id": "gBY3xIaDquY",
        "videoId": "gBY3xIaDquY",
        "title": "J'ai dépensé 50.000€ en moins d'1 an dans des formations (voici ce que j'ai appris)",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-08-02",
        "url": "https://www.youtube.com/watch?v=gBY3xIaDquY",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : J'ai dépensé 50.000€ en moins d'1 an dans des formations (voici ce que j'ai appris)...",
        "isShort": false
    },
    {
        "id": "_-oxY6Q8BBs",
        "videoId": "_-oxY6Q8BBs",
        "title": "L'outil IA n°1 sur Github vient de RÉSOUDRE le problème de recherche sur Claude",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-07-29",
        "url": "https://www.youtube.com/watch?v=_-oxY6Q8BBs",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : L'outil IA n°1 sur Github vient de RÉSOUDRE le problème de recherche sur Claude...",
        "isShort": false
    },
    {
        "id": "pk-_1sanvCw",
        "videoId": "pk-_1sanvCw",
        "title": "J'ai créé mes propres applis avec Claude (et vous pouvez aussi)",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-07-27",
        "url": "https://www.youtube.com/watch?v=pk-_1sanvCw",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : J'ai créé mes propres applis avec Claude (et vous pouvez aussi)...",
        "duration": 913,
        "isShort": false
    },
    {
        "id": "de8Dp2EWo0g",
        "videoId": "de8Dp2EWo0g",
        "title": "J'ai analysé 85 Agences IA, voici ce qui marche en 2026",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-07-26",
        "url": "https://www.youtube.com/watch?v=de8Dp2EWo0g",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : J'ai analysé 85 Agences IA, voici ce qui marche en 2026...",
        "isShort": false
    },
    {
        "id": "JIFgklJGj2w",
        "videoId": "JIFgklJGj2w",
        "title": "Arrêtez de créer des Agents IA, créez des Loops !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-07-23",
        "url": "https://www.youtube.com/watch?v=JIFgklJGj2w",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Arrêtez de créer des Agents IA, créez des Loops !...",
        "duration": 57,
        "isShort": true
    },
    {
        "id": "NQJPlvwVFOE",
        "videoId": "NQJPlvwVFOE",
        "title": "Comment Créer des Skills Claude comme un PRO (tuto complet)",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-07-22",
        "url": "https://www.youtube.com/watch?v=NQJPlvwVFOE",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Comment Créer des Skills Claude comme un PRO (tuto complet)...",
        "isShort": false
    },
    {
        "id": "FD0i-wFhnC4",
        "videoId": "FD0i-wFhnC4",
        "title": "Arrêtez les prompts. Passez aux Loops (Le futur des agents IA)",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-07-22",
        "url": "https://www.youtube.com/watch?v=FD0i-wFhnC4",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Arrêtez les prompts. Passez aux Loops (Le futur des agents IA)...",
        "duration": 2305,
        "isShort": false
    },
    {
        "id": "IziMU2lXstI",
        "videoId": "IziMU2lXstI",
        "title": "Ces 5 extensions rendent NotebookLM enfin complet",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-07-20",
        "url": "https://www.youtube.com/watch?v=IziMU2lXstI",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : Ces 5 extensions rendent NotebookLM enfin complet...",
        "duration": 1132,
        "isShort": false
    },
    {
        "id": "3q1slkjnJNE",
        "videoId": "3q1slkjnJNE",
        "title": "Comment je mène un Audit IA chez un client à 5M€ (extraits réels)",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-07-19",
        "url": "https://www.youtube.com/watch?v=3q1slkjnJNE",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Comment je mène un Audit IA chez un client à 5M€ (extraits réels)...",
        "isShort": false
    },
    {
        "id": "JnUPQ0lwgpI",
        "videoId": "JnUPQ0lwgpI",
        "title": "Voici Copilot Cowork, l'IA qui automatise vos tâches !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-07-16",
        "url": "https://www.youtube.com/watch?v=JnUPQ0lwgpI",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : Voici Copilot Cowork, l'IA qui automatise vos tâches !...",
        "duration": 36,
        "isShort": true
    },
    {
        "id": "C9oGaD_L29M",
        "videoId": "C9oGaD_L29M",
        "title": "J'ai testé l’énorme mise à jour de ChatGPT ! (ChatGPT Work + GPT-5.6)",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-07-13",
        "url": "https://www.youtube.com/watch?v=C9oGaD_L29M",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : J'ai testé l’énorme mise à jour de ChatGPT ! (ChatGPT Work + GPT-5.6)...",
        "duration": 52,
        "isShort": true
    },
    {
        "id": "Sj3Z1-LO-I8",
        "videoId": "Sj3Z1-LO-I8",
        "title": "Mon système pour publier régulièrement avec 1 jour par semaine",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-07-13",
        "url": "https://www.youtube.com/watch?v=Sj3Z1-LO-I8",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : Mon système pour publier régulièrement avec 1 jour par semaine...",
        "duration": 646,
        "isShort": false
    },
    {
        "id": "rx7F_9Vm35Y",
        "videoId": "rx7F_9Vm35Y",
        "title": "ChatGPT travaille enfin à votre place ! (ChatGPT Work & GPT-5.6)",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-07-12",
        "url": "https://www.youtube.com/watch?v=rx7F_9Vm35Y",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : ChatGPT travaille enfin à votre place ! (ChatGPT Work & GPT-5.6)...",
        "duration": 1775,
        "isShort": false
    },
    {
        "id": "ukf9DBoyas8",
        "videoId": "ukf9DBoyas8",
        "title": "L'étape que tout le monde saute avant de choisir son IA",
        "author": "Ludovic Nédélec",
        "source": "@LudovicNedelec",
        "date": "2026-06-29",
        "url": "https://www.youtube.com/watch?v=ukf9DBoyas8",
        "category": "Productivité & Second Cerveau",
        "summary": "Nouveauté de Ludovic Nédélec : L'étape que tout le monde saute avant de choisir son IA...",
        "duration": 998,
        "isShort": false
    },
    {
        "id": "ZCdYOnKdPp8",
        "videoId": "ZCdYOnKdPp8",
        "title": "Vendre une infrastructure IA 3000€ sans être un vendeur (Matrice POVI)",
        "author": "Simon Music",
        "source": "@Simon_bcome",
        "date": "2026-06-28",
        "url": "https://www.youtube.com/watch?v=ZCdYOnKdPp8",
        "category": "Business & Monétisation IA",
        "summary": "Nouveauté de Simon Music : Vendre une infrastructure IA 3000€ sans être un vendeur (Matrice POVI)...",
        "isShort": false
    },
    {
        "id": "JKD_mD70ml8",
        "videoId": "JKD_mD70ml8",
        "title": "J’ai confié mes tâches à Copilot Cowork : le résultat est bluffant !",
        "author": "Elliott Pierret",
        "source": "@elliottpierret",
        "date": "2026-06-28",
        "url": "https://www.youtube.com/watch?v=JKD_mD70ml8",
        "category": "Vibe Coding & Dev IA",
        "summary": "Nouveauté de Elliott Pierret : J’ai confié mes tâches à Copilot Cowork : le résultat est bluffant !...",
        "duration": 1219,
        "isShort": false
    }
];
